management:
  endpoints:
    web:
      exposure:
        include: health,prometheus # expose apis for health check and prometheus
  endpoint:
    health:
      show-details: when_authorized

services:
  user:
    destination:
      user-service-url: ${USER_SERVICE_URL} # TODO replace with service discovery