management:
  endpoints:
    web:
      exposure:
        include: health,prometheus # expose apis for health check and prometheus
  endpoint:
    health:
      show-details: when_authorized
jwt:
  secret-key: ${JWT_SECRET_KEY}

spring:
  application:
    name: api-gateway-v1
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: ${ZIPKIN_URL}
    sender:
      type: rabbit
  rabbitmq:
    host: ${RABBIT_MQ_HOST}
    port: ${RABBIT_MQ_PORT}
    username: ${RABBIT_MQ_USERNAME}
    password: ${RABBIT_MQ_PASSWORD}
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${USER_SERVICE_HOST}:${USER_SERVICE_PORT}
          predicates:
            - Path=/users/**
        - id: authority-service
          uri: ${AUTHORITY_SERVICE_HOST}:${AUTHORITY_SERVICE_ENDPOINT}
          predicates:
            - Path=/authorities/**